# Generated by Django 5.2.7 on 2025-11-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apartment_number',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
