# Generated by Django 5.0.6 on 2026-01-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='due',
            name='type',
            field=models.CharField(choices=[('aidat', 'Aidat'), ('bakim', 'Bakım Ücreti'), ('onarim', 'Onarım'), ('elektrik', 'Ortak Alan Elektrik'), ('ozel', 'Özel Ödeme')], default='aidat', max_length=20),
        ),
    ]
