# Generated by Django 5.0.6 on 2026-01-01 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fix_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.due'),
        ),
    ]
